# Parte 3: Estudio de diferentes algoritmos de machine learning

En este notebook vamos a aplicar diferentes algoritmos para estudiar su efectividad para este problema e intentaremos predicciones para los Juegos Olímpicos de 2021.

Los algoritmos que se aplican son: 
* Datos de entrenamiento y datos de test
* Knn - Vecinos cercanos
* Regresión Lineal
* Regresión Logística
* Naive Bayes
* Gaussian Naive Bayes
* K-means
* Perceptron
* MLP - Multi layer perceptron
* Curva ROC
* Decision Tree
* SVM - Supervised Vector Machine
* Descenso del gradiente
* Random Forest
* ¿¿RED NEURONAL??

In [19]:
import pandas as pd

import numpy as np
from numpy import * 

import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import plot_confusion_matrix

from sklearn.neighbors import KNeighborsClassifier
from sklearn import linear_model
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.cluster import KMeans
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import multilabel_confusion_matrix

#confusion_matrix = confusion_matrix(y_test, y_pred)
#print(confusion_matrix)
#from sklearn.metrics import classification_report
#print(classification_report(y_test, y_pred))

In [20]:
#Lee el excel generado en el otro documento .ipynb
ddbb=pd.read_excel("/Github/DecatlonEstadistics/resources/data.xlsx")
del ddbb['1500m NF']

ddbb['Country']=ddbb['Country'].str.lower()

ddbb.columns = ['Position', 'Athlete', 'Age', 'Country', 'Total Points', 'Year', 'Competition', '100m', 
                 '100m Points', 'Lj', 'Lj Points', 'Sp', 'Sp Points', 'Hj', 'Hj Points', '400m', '400m Points', 
                 '110m H', '110m H Points', 'Dt', 'Dt Points', 'Pv', 'Pv Points', 'Jt', 'Jt Points', 
                 '1500m Points', '1500m']

## 1. Datos de entrenamiento y datos de test.

Los datos se entrenan en función a todas las pruebas resultantes y se clasifican en función a la posición obtenida.
El 70% de los datos se utilizan para entrenamiento.
El 30% restante se utiliza para tests.

In [21]:
ddbbData = ddbb[['100m','100m Points','Lj','Lj Points','Sp','Sp Points','Hj','Hj Points','400m Points','400m',
                 '110m H','110m H Points','Dt','Dt Points','Pv','Pv Points','Jt','Jt Points','1500m Points','1500m']]

X_train, X_test, y_train, y_test = train_test_split(ddbbData, ddbb['Position'], test_size=0.3)

## 2. Vecinos Cercanos

In [32]:
knn = KNeighborsClassifier(n_neighbors=5)

#Entrena el modelo
knn.fit(X_train, y_train)

#Predice para los datos de test
y_pred = knn.predict(X_test)

matrizConfusion = multilabel_confusion_matrix(y_test, y_pred,labels=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,
                                                    22,23,24,25,26,27,28,29,30,31,32,33,34])
 
print(pene)
    
print('El accuracy en Vecinos Cercanos es: {:.3f}'.format(knn.score(X_test, y_test)))

[[[222  25]
  [  1   7]]

 [[229  18]
  [  7   1]]

 [[219  20]
  [ 15   1]]

 [[226  17]
  [ 10   2]]

 [[225  17]
  [ 12   1]]

 [[226  20]
  [  8   1]]

 [[237   9]
  [  9   0]]

 [[232  16]
  [  7   0]]

 [[224  22]
  [  9   0]]

 [[230  12]
  [ 13   0]]

 [[231  10]
  [ 12   2]]

 [[234   7]
  [ 14   0]]

 [[242   6]
  [  7   0]]

 [[241   0]
  [ 13   1]]

 [[238   1]
  [ 16   0]]

 [[232  10]
  [ 13   0]]

 [[237   9]
  [  9   0]]

 [[245   0]
  [ 10   0]]

 [[245   2]
  [  8   0]]

 [[242   4]
  [  9   0]]

 [[250   0]
  [  5   0]]

 [[242   6]
  [  7   0]]

 [[245   5]
  [  5   0]]

 [[250   1]
  [  4   0]]

 [[251   0]
  [  4   0]]

 [[253   0]
  [  2   0]]

 [[254   0]
  [  1   0]]

 [[252   2]
  [  1   0]]

 [[254   0]
  [  1   0]]

 [[253   0]
  [  2   0]]

 [[253   0]
  [  2   0]]

 [[253   0]
  [  2   0]]

 [[254   0]
  [  1   0]]

 [[255   0]
  [  0   0]]]
El accuracy en Vecinos Cercanos es: 0.063


## 3. Regresión Lineal

In [5]:
regL = linear_model.LinearRegression()

regL.fit(X_train, y_train)

y_pred = regL.predict(X_test)

print('El accuracy en Regresión Linear es: {:.3f}'.format(regL.score(X_test, y_test)))

El accuracy en Regresión Linear es: 0.485


## 4. Regresión Logística

In [6]:
logreg = linear_model.LogisticRegression(random_state=0)

logreg.fit(X_train, y_train)

y_pred = logreg.predict(X_test)

print('El accuracy en Regresión Logistica es:: {:.3f}'.format(logreg.score(X_test, y_test)))

El accuracy en Regresión Logistica es:: 0.055


/opt/conda/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


## 5. Naive Bayes

In [7]:
gnb = GaussianNB()

gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

print('El accuracy en Naive Bayes es:: {:.3f}'.format(gnb.score(X_test, y_test)))

El accuracy en Naive Bayes es:: 0.059


##  6. K-Means

In [10]:
kmeans = KMeans(n_clusters=2)

kmeans = KMeans(n_clusters=5).fit(ddbbData)
centroids = kmeans.cluster_centers_
print(centroids)

[[1.15503670e+01 7.10403670e+02 6.54231651e+00 7.06518849e+02
  1.21625688e+01 6.16591743e+02 1.75802752e+00 5.94348624e+02
  6.97288991e+02 5.26285780e+01 1.63089908e+01 6.50724972e+02
  3.65132110e+01 5.91853211e+02 3.16000000e+00 4.08968550e+02
  4.98710321e+01 5.87720183e+02 5.85619266e+02 2.86856321e+02]
 [1.10037480e+01 8.59363285e+02 7.25082935e+00 8.58912069e+02
  1.43604466e+01 7.51174450e+02 1.98925040e+00 7.94833078e+02
  8.54498262e+02 4.90530463e+01 1.46562998e+01 8.83336638e+02
  4.41049761e+01 7.49105423e+02 4.72647528e+00 8.28708182e+02
  6.01726954e+01 7.37621743e+02 6.93311802e+02 2.77283043e+02]
 [1.13350000e+01 7.76000000e+02 6.68000000e+00 7.39000000e+02
  1.29150000e+01 6.62500000e+02 1.87000000e+00 6.88000000e+02
  8.12000000e+02 5.00750000e+01 1.57050000e+01 7.67500000e+02
  3.80400000e+03 6.25000000e+02 3.85000000e+00 5.79500000e+02
  5.46800000e+01 6.58000000e+02 6.77000000e+02 2.80800000e+02]
 [1.11800000e+01 8.21000000e+02 6.88000000e+02 7.85000000e+02
  1.3

## 7. Perceptron

In [10]:
percep = Perceptron(tol=1e-5, random_state=1)

percep.fit(X_train, y_train)

y_pred = percep.predict(X_test)

print('El accuracy en Perceptron es:: {:.3f}'.format(percep.score(X_test, y_test)))

El accuracy en Perceptron es:: 0.067


## 8. MLP- Perceptron Multi Capa

In [11]:
mlp = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)

mlp.fit(X_train, y_train)

y_pred = mlp.predict(X_test)

print('El accuracy en MLP es:: {:.3f}'.format(mlp.score(X_test, y_test)))

El accuracy en MLP es:: 0.031


## 9. SVM - Supervised Vector Machine

In [ ]:
clf = svm.SVC(kernel='linear')

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print('El accuracy en SVM es:: {:.3f}'.format(clf.score(X_test, y_test)))

## 10. Descenso del gradiente

In [ ]:
dGrad = SGDClassifier(loss="hinge", penalty="l2")

dGrad.fit(X_train, y_train)

y_pred = dGrad.predict(X_test)

print('El accuracy en Descenso del gradiente es:: {:.3f}'.format(dGrad.score(X_test, y_test)))

## 11. Arbol de decision

In [ ]:
clf = DecisionTreeClassifier(criterion="entropy", max_depth=3)

clf = clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

print('El accuracy en SVM es:: {:.3f}'.format(clf.score(X_test, y_test)))

## 12. Random Forest

In [ ]:
rForest=RandomForestClassifier(n_estimators=100)

rForest.fit(X_train,y_train)

y_pred=rForest.predict(X_test)

print('El accuracy en Random Forest es:: {:.3f}'.format(rForest.score(X_test, y_test)))